[build]
  command = "echo 'Netlify does not support Python Flask apps. Please use Railway, Render, or Heroku instead.'"
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
